name = "mein-blazor-app"
type = "javascript"
account_id = "DEIN_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "dotnet publish -c Release -o build"
upload.format = "service-worker"
upload.dir = "build/wwwroot"
